import re

str1="^AA+(B+|A+)(B+|A+)AA+(B+|A+)(B+|A+)AAA+(B+|A+)AA+(B+|A+)(B+|A+)(B+|A+)(B+|A+)AA+(B+|A+)AA+(B+|A+)(B+|A+)(B+|A+)AAAA+(B+|A+)(B+|A+)AAA+(B+|A+)(B+|A+)AA+(B+|A+)(B+|A+)(B+|A+)AA+(B+|A+)A+(B+|A+)AA+(B+|A+)(B+|A+)A+(B+|A+)AAA+(B+|A+)(B+|A+)A+(B+|A+)(B+|A+)(B+|A+)(B+|A+)A+(B+|A+)AAA+(B+|A+)A+(B+|A+)A+(B+|A+)(B+|A+)(B+|A+)(B+|A+)A+(B+|A+)A+$"

test1="AAAAAAABBBAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBAAAAAAAAAABAAAAAABBBAAAAAAAAAAAAAABBBBAAAAAAAABBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAABBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBAAAAAAAAAAAABBBAAAAAABBBBBBAAAAAAAAAAABBBBAAAAAAAAAAAAAAAAAAAAAAAAAAABBAAAAAAAAAAAAAAAAAAAABBBBAAAAAAAABBBBBAAAAAAAAAAAAABBBAAAAAAAAAAABBBBBBBBBBBBBBBAAAAAABBBAA"

re.match(str1,test1)
