import re

str1="^AA+(B+|A+){2}AA+(B+|A+){2}AAA+(B+|A+)AA+(B+|A+){4}AA+(B+|A+)AA+(B+|A+){3}AAAA+(B+|A+){2}AAA+(B+|A+){2}AA+(B+|A+){3}AA+(B+|A+)A+(B+|A+)AA+(B+|A+){2}A+(B+|A+)AAA+(B+|A+){2}A+(B+|A+){4}A+(B+|A+)AAA+(B+|A+)A+(B+|A+)A+(B+|A+){4}A+(B+|A+)A+$"

test1="AAAAAAABBBAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBAAAAAAAAAABAAAAAABBBAAAAAAAAAAAAAABBBBAAAAAAAABBBBBBBBBBBBAAAAAAAAAAAAAAAAAAAAAABBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBAAAAAAAAAAAABBBAAAAAABBBBBBAAAAAAAAAAABBBBAAAAAAAAAAAAAAAAAAAAAAAAAAABBAAAAAAAAAAAAAAAAAAAABBBBAAAAAAAABBBBBAAAAAAAAAAAAABBBAAAAAAAAAAABBBBBBBBBBBBBBBAAAAAABBBAA"

re.match(str1,test1)
